channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.1.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
